/*
-- Query: SELECT * FROM dashboard.aux_literales
-- Date: 2023-11-14 11:51
*/
USE dashboard;
INSERT INTO aux_literales (`id`,`vc_type`,`vc_subtype`,`vc_ord`,`vc_desc`) VALUES (28,'Engagement Managers','t',0,'TOTAL #EM of the unit + specific focus on #EM with experience in Complex Solutions  engagements +specific focus on #EM with effective Agile and Product Centric experience +#certified EM');
INSERT INTO aux_literales (`id`,`vc_type`,`vc_subtype`,`vc_ord`,`vc_desc`) VALUES (29,'Engagement Managers','c',1,'Engagement Managers');
INSERT INTO aux_literales (`id`,`vc_type`,`vc_subtype`,`vc_ord`,`vc_desc`) VALUES (30,'Engagement Managers','c',2,'TOTAL');
INSERT INTO aux_literales (`id`,`vc_type`,`vc_subtype`,`vc_ord`,`vc_desc`) VALUES (31,'Engagement Managers','c',3,'with complex solutions');
INSERT INTO aux_literales (`id`,`vc_type`,`vc_subtype`,`vc_ord`,`vc_desc`) VALUES (32,'Engagement Managers','c',4,'Agile & Product Centricity');
INSERT INTO aux_literales (`id`,`vc_type`,`vc_subtype`,`vc_ord`,`vc_desc`) VALUES (33,'Engagement Managers','r',1,'Engagement Managers');
INSERT INTO aux_literales (`id`,`vc_type`,`vc_subtype`,`vc_ord`,`vc_desc`) VALUES (34,'Engagement Managers','r',2,'Others (***) - (PMO, …)');
INSERT INTO aux_literales (`id`,`vc_type`,`vc_subtype`,`vc_ord`,`vc_desc`) VALUES (35,'Architects','t',0,'TOTAL #Architects of the unit + specific focus on #Archi with experience in Complex Solutions  architecture & roadmaps + specific focus on #Archi with effective Agile and Product Centric experience+ #certified Architects');
INSERT INTO aux_literales (`id`,`vc_type`,`vc_subtype`,`vc_ord`,`vc_desc`) VALUES (36,'Architects','c',1,'Architects');
INSERT INTO aux_literales (`id`,`vc_type`,`vc_subtype`,`vc_ord`,`vc_desc`) VALUES (37,'Architects','c',2,'TOTAL');
INSERT INTO aux_literales (`id`,`vc_type`,`vc_subtype`,`vc_ord`,`vc_desc`) VALUES (38,'Architects','c',3,'with complex solutions');
INSERT INTO aux_literales (`id`,`vc_type`,`vc_subtype`,`vc_ord`,`vc_desc`) VALUES (39,'Architects','c',4,'Agile & Product Centricity');
INSERT INTO aux_literales (`id`,`vc_type`,`vc_subtype`,`vc_ord`,`vc_desc`) VALUES (40,'Architects','r',1,'Enterprise Architects');
INSERT INTO aux_literales (`id`,`vc_type`,`vc_subtype`,`vc_ord`,`vc_desc`) VALUES (41,'Architects','r',2,'Business Architects');
INSERT INTO aux_literales (`id`,`vc_type`,`vc_subtype`,`vc_ord`,`vc_desc`) VALUES (42,'Architects','r',3,'Solution Architects');
INSERT INTO aux_literales (`id`,`vc_type`,`vc_subtype`,`vc_ord`,`vc_desc`) VALUES (43,'Architects','r',4,'Integration Architects');
INSERT INTO aux_literales (`id`,`vc_type`,`vc_subtype`,`vc_ord`,`vc_desc`) VALUES (44,'Business Analyst','t',0,'TOTAL #BusinessAnalysts of the unit +certified Business Analysts');
INSERT INTO aux_literales (`id`,`vc_type`,`vc_subtype`,`vc_ord`,`vc_desc`) VALUES (45,'Business Analyst','c',1,'Business Analysts');
INSERT INTO aux_literales (`id`,`vc_type`,`vc_subtype`,`vc_ord`,`vc_desc`) VALUES (46,'Business Analyst','c',2,'TOTAL');
INSERT INTO aux_literales (`id`,`vc_type`,`vc_subtype`,`vc_ord`,`vc_desc`) VALUES (48,'Software Engineer','t',0,'TOTAL #Software Engineers of the unit');
INSERT INTO aux_literales (`id`,`vc_type`,`vc_subtype`,`vc_ord`,`vc_desc`) VALUES (49,'Software Engineer','c',1,'Software Engineers');
INSERT INTO aux_literales (`id`,`vc_type`,`vc_subtype`,`vc_ord`,`vc_desc`) VALUES (50,'Software Engineer','c',2,'TOTAL');
INSERT INTO aux_literales (`id`,`vc_type`,`vc_subtype`,`vc_ord`,`vc_desc`) VALUES (51,'Industry Experts','t',0,'TOTAL #Industry Experts of the unit');
INSERT INTO aux_literales (`id`,`vc_type`,`vc_subtype`,`vc_ord`,`vc_desc`) VALUES (52,'Industry Experts','c',1,'Industry Experts');
INSERT INTO aux_literales (`id`,`vc_type`,`vc_subtype`,`vc_ord`,`vc_desc`) VALUES (53,'Industry Experts','c',2,'TOTAL');
INSERT INTO aux_literales (`id`,`vc_type`,`vc_subtype`,`vc_ord`,`vc_desc`) VALUES (54,'Industry Experts','c',3,'Consumer Goods & Retail');
INSERT INTO aux_literales (`id`,`vc_type`,`vc_subtype`,`vc_ord`,`vc_desc`) VALUES (55,'Industry Experts','c',4,'Energy & Utilities');
INSERT INTO aux_literales (`id`,`vc_type`,`vc_subtype`,`vc_ord`,`vc_desc`) VALUES (56,'Industry Experts','c',5,'Manufacturing');
INSERT INTO aux_literales (`id`,`vc_type`,`vc_subtype`,`vc_ord`,`vc_desc`) VALUES (57,'Industry Experts','c',6,'Life Science');
INSERT INTO aux_literales (`id`,`vc_type`,`vc_subtype`,`vc_ord`,`vc_desc`) VALUES (58,'Industry Experts','c',7,'Public Sector');
INSERT INTO aux_literales (`id`,`vc_type`,`vc_subtype`,`vc_ord`,`vc_desc`) VALUES (59,'Industry Experts','c',8,'Telco, Media & Technologies');
INSERT INTO aux_literales (`id`,`vc_type`,`vc_subtype`,`vc_ord`,`vc_desc`) VALUES (60,'Industry Experts','c',9,'Financial Services');
INSERT INTO aux_literales (`id`,`vc_type`,`vc_subtype`,`vc_ord`,`vc_desc`) VALUES (61,'Architects & SE Custom Apps Development','t',0,'Focus on #Architects + #SoftwareEngineers of the unit able to design, build, deliver and deploy Custom Applications. + specific focus on #Architects + #SoftwareEngineers with expertise on Hyperscaler native services + specific focus on #Architects + #SoftwareEngineers with expertise on Low Code');
INSERT INTO aux_literales (`id`,`vc_type`,`vc_subtype`,`vc_ord`,`vc_desc`) VALUES (62,'Architects & SE Custom Apps Development','c',1,'Architects & SE Custom Apps Development');
INSERT INTO aux_literales (`id`,`vc_type`,`vc_subtype`,`vc_ord`,`vc_desc`) VALUES (63,'Architects & SE Custom Apps Development','c',2,'TOTAL');
INSERT INTO aux_literales (`id`,`vc_type`,`vc_subtype`,`vc_ord`,`vc_desc`) VALUES (64,'Architects & SE Custom Apps Development','c',3,'SW Dev Back end Java');
INSERT INTO aux_literales (`id`,`vc_type`,`vc_subtype`,`vc_ord`,`vc_desc`) VALUES (65,'Architects & SE Custom Apps Development','c',4,'SW Dev Back end .Net');
INSERT INTO aux_literales (`id`,`vc_type`,`vc_subtype`,`vc_ord`,`vc_desc`) VALUES (66,'Architects & SE Custom Apps Development','c',5,'SW Dev Full Stack Java');
INSERT INTO aux_literales (`id`,`vc_type`,`vc_subtype`,`vc_ord`,`vc_desc`) VALUES (67,'Architects & SE Custom Apps Development','c',6,'SW Dev Full Stack .Net');
INSERT INTO aux_literales (`id`,`vc_type`,`vc_subtype`,`vc_ord`,`vc_desc`) VALUES (68,'Architects & SE Custom Apps Development','c',7,'SW Dev Front End');
INSERT INTO aux_literales (`id`,`vc_type`,`vc_subtype`,`vc_ord`,`vc_desc`) VALUES (69,'Architects & SE Custom Apps Development','c',8,'SW Dev Mainframe');
INSERT INTO aux_literales (`id`,`vc_type`,`vc_subtype`,`vc_ord`,`vc_desc`) VALUES (70,'Architects & SE Custom Apps Development','c',9,'DevOps Automation');
INSERT INTO aux_literales (`id`,`vc_type`,`vc_subtype`,`vc_ord`,`vc_desc`) VALUES (71,'Architects & SE Custom Apps Development','c',10,'Other');
INSERT INTO aux_literales (`id`,`vc_type`,`vc_subtype`,`vc_ord`,`vc_desc`) VALUES (72,'Architects & SE Custom Apps Development','c',11,'AWS');
INSERT INTO aux_literales (`id`,`vc_type`,`vc_subtype`,`vc_ord`,`vc_desc`) VALUES (73,'Architects & SE Custom Apps Development','c',12,'Azure');
INSERT INTO aux_literales (`id`,`vc_type`,`vc_subtype`,`vc_ord`,`vc_desc`) VALUES (74,'Architects & SE Custom Apps Development','c',13,'GCP');
INSERT INTO aux_literales (`id`,`vc_type`,`vc_subtype`,`vc_ord`,`vc_desc`) VALUES (75,'Architects & SE Custom Apps Development','c',14,'Other clouds');
INSERT INTO aux_literales (`id`,`vc_type`,`vc_subtype`,`vc_ord`,`vc_desc`) VALUES (76,'Architects & SE Custom Apps Development','c',15,'Outsystems');
INSERT INTO aux_literales (`id`,`vc_type`,`vc_subtype`,`vc_ord`,`vc_desc`) VALUES (77,'Architects & SE Custom Apps Development','c',16,'PowerApps');
INSERT INTO aux_literales (`id`,`vc_type`,`vc_subtype`,`vc_ord`,`vc_desc`) VALUES (78,'Architects & SE Custom Apps Development','c',17,'Mendix');
INSERT INTO aux_literales (`id`,`vc_type`,`vc_subtype`,`vc_ord`,`vc_desc`) VALUES (79,'Architects & SE Custom Apps Development','c',18,'Others');
INSERT INTO aux_literales (`id`,`vc_type`,`vc_subtype`,`vc_ord`,`vc_desc`) VALUES (80,'Architects & SE Custom Apps Development','r',1,'Solution Architects');
INSERT INTO aux_literales (`id`,`vc_type`,`vc_subtype`,`vc_ord`,`vc_desc`) VALUES (81,'Architects & SE Custom Apps Development','r',2,'Software Engineers');
INSERT INTO aux_literales (`id`,`vc_type`,`vc_subtype`,`vc_ord`,`vc_desc`) VALUES (82,'Architects & SE Integration & APIs','t',0,'Focus on #Architects and #IntegrationEngineers of the unit able to design, build, deliver and deploy Integration & APIs platforms');
INSERT INTO aux_literales (`id`,`vc_type`,`vc_subtype`,`vc_ord`,`vc_desc`) VALUES (83,'Architects & SE Integration & APIs','c',1,'Architects & SE Integration & APIs');
INSERT INTO aux_literales (`id`,`vc_type`,`vc_subtype`,`vc_ord`,`vc_desc`) VALUES (84,'Architects & SE Integration & APIs','c',2,'TOTAL');
INSERT INTO aux_literales (`id`,`vc_type`,`vc_subtype`,`vc_ord`,`vc_desc`) VALUES (85,'Architects & SE Integration & APIs','c',3,'Mulesoft');
INSERT INTO aux_literales (`id`,`vc_type`,`vc_subtype`,`vc_ord`,`vc_desc`) VALUES (86,'Architects & SE Integration & APIs','c',4,'Boomi');
INSERT INTO aux_literales (`id`,`vc_type`,`vc_subtype`,`vc_ord`,`vc_desc`) VALUES (87,'Architects & SE Integration & APIs','c',5,'Software AG');
INSERT INTO aux_literales (`id`,`vc_type`,`vc_subtype`,`vc_ord`,`vc_desc`) VALUES (88,'Architects & SE Integration & APIs','c',6,'Tibco');
INSERT INTO aux_literales (`id`,`vc_type`,`vc_subtype`,`vc_ord`,`vc_desc`) VALUES (89,'Architects & SE Integration & APIs','c',7,'Other vendor');
INSERT INTO aux_literales (`id`,`vc_type`,`vc_subtype`,`vc_ord`,`vc_desc`) VALUES (90,'Architects & SE Integration & APIs','c',8,'Open Source');
INSERT INTO aux_literales (`id`,`vc_type`,`vc_subtype`,`vc_ord`,`vc_desc`) VALUES (91,'Architects & SE Integration & APIs','r',1,'Integration Architects');
INSERT INTO aux_literales (`id`,`vc_type`,`vc_subtype`,`vc_ord`,`vc_desc`) VALUES (92,'Architects & SE Integration & APIs','r',2,'Software Engineers');
INSERT INTO aux_literales (`id`,`vc_type`,`vc_subtype`,`vc_ord`,`vc_desc`) VALUES (93,'Pyramid Grade-Rol','t',0,'Grade #pyramid for the population');
INSERT INTO aux_literales (`id`,`vc_type`,`vc_subtype`,`vc_ord`,`vc_desc`) VALUES (94,'Pyramid Grade-Rol','c',1,'Engagement Managers');
INSERT INTO aux_literales (`id`,`vc_type`,`vc_subtype`,`vc_ord`,`vc_desc`) VALUES (95,'Pyramid Grade-Rol','c',2,'Architects');
INSERT INTO aux_literales (`id`,`vc_type`,`vc_subtype`,`vc_ord`,`vc_desc`) VALUES (96,'Pyramid Grade-Rol','c',3,'Business Analyst');
INSERT INTO aux_literales (`id`,`vc_type`,`vc_subtype`,`vc_ord`,`vc_desc`) VALUES (97,'Pyramid Grade-Rol','c',4,'Software Engineer');
INSERT INTO aux_literales (`id`,`vc_type`,`vc_subtype`,`vc_ord`,`vc_desc`) VALUES (98,'Pyramid Grade-Rol','r',1,'F');
INSERT INTO aux_literales (`id`,`vc_type`,`vc_subtype`,`vc_ord`,`vc_desc`) VALUES (99,'Pyramid Grade-Rol','r',2,'E');
INSERT INTO aux_literales (`id`,`vc_type`,`vc_subtype`,`vc_ord`,`vc_desc`) VALUES (100,'Pyramid Grade-Rol','r',3,'D');
INSERT INTO aux_literales (`id`,`vc_type`,`vc_subtype`,`vc_ord`,`vc_desc`) VALUES (101,'Pyramid Grade-Rol','r',4,'C');
INSERT INTO aux_literales (`id`,`vc_type`,`vc_subtype`,`vc_ord`,`vc_desc`) VALUES (102,'Pyramid Grade-Rol','r',5,'B');
INSERT INTO aux_literales (`id`,`vc_type`,`vc_subtype`,`vc_ord`,`vc_desc`) VALUES (103,'Pyramid Grade-Rol','r',6,'A');
INSERT INTO aux_literales (`id`,`vc_type`,`vc_subtype`,`vc_ord`,`vc_desc`) VALUES (104,'Business Analyst','r',1,'Business Analysts');
INSERT INTO aux_literales (`id`,`vc_type`,`vc_subtype`,`vc_ord`,`vc_desc`) VALUES (105,'Software Engineer','r',1,'Software Engineers');
INSERT INTO aux_literales (`id`,`vc_type`,`vc_subtype`,`vc_ord`,`vc_desc`) VALUES (106,'Industry Experts','r',1,'Industry Experts');
